
# Config for Phase 1 data collection
timezone: "Asia/Kolkata"
default_days_back: 0  # when --date not provided, collect for today

feeds:
  # === Add/curate feeds here ===
  # Official NSE RSS hub (choose specific feeds from the site)
  # Visit https://www.nseindia.com/rss-feed and copy concrete feed URLs
  # - "h/ttps://nsearchives.nseindia.com/content/RSS/Online_announcements.xml"   
  # - "https://nsearchives.nseindia.com/content/RSS/Annual_Reports.xml"
  - "https://cfo.economictimes.indiatimes.com/rss/topstories"
  - "https://cfo.economictimes.indiatimes.com/rss/recentstories"
  - "https://cfo.economictimes.indiatimes.com/rss/corporate-finance"
  - "https://cfo.economictimes.indiatimes.com/rss/governance-risk-compliance"
 
nse_corporate_announcements:
  enabled: false  # NSE blocks bots aggressively; enable after testing headers & cookies
  from_days_back: 0
  to_days_back: 0
  # The API often requires proper session cookies + headers. If you enable this, test locally first.
  # endpoint_template: "https://www.nseindia.com/api/corporate-announcements?index=equities&from_date={from_date}&to_date={to_date}"
  # headers:
  #   User-Agent: ${HTTP_USER_AGENT}
  #   Accept: "application/json, text/plain, */*"
  #   Referer: "https://www.nseindia.com/"
  #   Connection: "keep-alive"
  #   Accept-Language: "en-US,en;q=0.9"

storage:
  sqlite_path: "db/news.db"
  json_out_dir: "data/raw"
