
name: Daily News Ingest

on:
  schedule:
    # 09:07 IST = 03:37 UTC (Mon-Fri)
    - cron: '37 3 * * 1-5'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run collector (IST day)
        env:
          TZ: Asia/Kolkata
        run: |
          python -m src.data_fetch --date today  

      - name: Upload artifacts (raw JSON)
        uses: actions/upload-artifact@v4
        with:
          name: news-json
          path: data/raw/*.json
          if-no-files-found: ignore
